// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ql95GODjpmc4lQSAT8pNAwLENH8K0TU',
    appId: '1:1045023020495:web:024d9370b4b0bf7e9aeeba',
    messagingSenderId: '1045023020495',
    projectId: 'daycarefirst-7279c',
    authDomain: 'daycarefirst-7279c.firebaseapp.com',
    storageBucket: 'daycarefirst-7279c.firebasestorage.app',
    measurementId: 'G-4FE0YPHD6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ow2PhpiZQg0Jx_o_iGTUqM_PtmldnFk',
    appId: '1:1045023020495:android:925ae37f3f0abf159aeeba',
    messagingSenderId: '1045023020495',
    projectId: 'daycarefirst-7279c',
    storageBucket: 'daycarefirst-7279c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVm4AF0Xs8Q3ntsHOXcFQxY637YQZm7N8',
    appId: '1:1045023020495:ios:0a52d0223a541d1b9aeeba',
    messagingSenderId: '1045023020495',
    projectId: 'daycarefirst-7279c',
    storageBucket: 'daycarefirst-7279c.firebasestorage.app',
    iosBundleId: 'com.example.daycarefirst',
  );
}
